In [67]:
import numpy as np
import pandas as pd

In [68]:
df=pd.read_csv('cardio_train.csv',sep=';')

In [69]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [91]:
x = df.drop(['cardio', 'id'],axis=1)
x

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active
0,18393,2,168,62.0,110,80,1,1,0,0,1
1,20228,1,156,85.0,140,90,3,1,0,0,1
2,18857,1,165,64.0,130,70,3,1,0,0,0
3,17623,2,169,82.0,150,100,1,1,0,0,1
4,17474,1,156,56.0,100,60,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
69995,19240,2,168,76.0,120,80,1,1,1,0,1
69996,22601,1,158,126.0,140,90,2,2,0,0,1
69997,19066,2,183,105.0,180,90,3,1,0,1,0
69998,22431,1,163,72.0,135,80,1,2,0,0,0
69999,20540,1,170,72.0,120,80,2,1,0,0,1

In [92]:
y=df.cardio
y

0        0
1        1
2        1
3        1
4        0
        ..
69995    0
69996    1
69997    1
69998    1
69999    0
Name: cardio, Length: 70000, dtype: int64

In [93]:
from sklearn.feature_selection import SelectKBest

###  1. f_classif (target variable is categorical and your input features are numerical)

In [94]:
from sklearn.feature_selection import f_classif

In [95]:
selector=SelectKBest(score_func=f_classif)

In [96]:
selector.fit(x,y)

SelectKBest()

In [97]:
selector.scores_

array([4.20900796e+03, 4.60364136e+00, 8.19739692e+00, 2.38877789e+03,
       2.08339524e+02, 3.03629011e+02, 3.59936114e+03, 5.62772977e+02,
       1.67905412e+01, 3.76135544e+00, 8.90914938e+01])

In [98]:
score_col = pd.DataFrame(data=selector.scores_, columns=['score'])
score_col

          score
0   4209.007957
1      4.603641
2      8.197397
3   2388.777887
4    208.339524
5    303.629011
6   3599.361137
7    562.772977
8     16.790541
9      3.761355
10    89.091494

In [99]:
Name_col=pd.DataFrame(data=x.columns,columns=['selector'])
Name_col

       selector
0           age
1        gender
2        height
3        weight
4         ap_hi
5         ap_lo
6   cholesterol
7          gluc
8         smoke
9          alco
10       active

In [100]:
selector_score=pd.concat([Name_col,score_col], axis=1)
selector_score

       selector        score
0           age  4209.007957
1        gender     4.603641
2        height     8.197397
3        weight  2388.777887
4         ap_hi   208.339524
5         ap_lo   303.629011
6   cholesterol  3599.361137
7          gluc   562.772977
8         smoke    16.790541
9          alco     3.761355
10       active    89.091494

In [101]:
selector_score.nlargest(8,'score')

       selector        score
0           age  4209.007957
6   cholesterol  3599.361137
3        weight  2388.777887
7          gluc   562.772977
5         ap_lo   303.629011
4         ap_hi   208.339524
10       active    89.091494
8         smoke    16.790541

### 2.Chi2 (for non- negative inputs)

In [102]:
from sklearn.feature_selection import chi2

selector = SelectKBest(score_func=chi2)

In [103]:
# Find all negative values in x
(x < 0).sum()

age            0
gender         0
height         0
weight         0
ap_hi          7
ap_lo          1
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
dtype: int64

In [104]:
valid = (x['ap_hi'] >= 0) & (x['ap_lo'] >= 0)

x = x.loc[valid]
y = y.loc[valid]

In [105]:
selector.fit(x,y)

SelectKBest(score_func=<function chi2 at 0x000001F5962EC900>)

In [106]:
score_col = pd.DataFrame(data=selector.scores_, columns=['score'])
Name_col = pd.DataFrame(data=x.columns, columns=['selector'])
selector_score = pd.concat([Name_col, score_col], axis=1)
selector_score.nlargest(8, 'score')

       selector         score
0           age  1.241407e+06
5         ap_lo  1.111740e+05
4         ap_hi  3.824031e+04
3        weight  6.453557e+03
6   cholesterol  1.159072e+03
7          gluc  1.490914e+02
10       active  1.746624e+01
8         smoke  1.530754e+01

### 3.mutual_info_classif(including nonlinear relationships)

In [107]:
from sklearn.feature_selection import mutual_info_classif

In [108]:
selector = SelectKBest(score_func=mutual_info_classif)

In [109]:
selector.fit(x,y)

SelectKBest(score_func=<function mutual_info_classif at 0x000001F5962D2AC0>)

In [110]:
score_col = pd.DataFrame(data=selector.scores_, columns=['score'])
Name_col = pd.DataFrame(data=x.columns, columns=['selector'])
selector_score = pd.concat([Name_col, score_col], axis=1)
selector_score.nlargest(8, 'score')

       selector     score
4         ap_hi  0.120920
5         ap_lo  0.077322
0           age  0.034216
6   cholesterol  0.028311
3        weight  0.020381
10       active  0.010208
7          gluc  0.008719
1        gender  0.004705