In [3]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)

In [51]:
df= pd.DataFrame(randn(5,4),["A","b","c","d","e"],["w","x","y","z"])

In [5]:
df

          w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [6]:
df["w"]

A    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [7]:
type(df["w"])

pandas.core.series.Series

In [9]:
df[["w","y"]]

          w         y
A  2.706850  0.907969
b  0.651118 -0.848077
c -2.018168  0.528813
d  0.188695 -0.933237
e  0.190794  2.605967

In [11]:
df["new"]=df["w"]+df["y"]

In [12]:
df

          w         x         y         z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [18]:
df.drop('new', axis=1)

          w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [19]:
df

          w         x         y         z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
df.drop('new', axis=1, inplace=True)

In [27]:
df

          w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [29]:
df.shape

(5, 4)

In [35]:
df.loc[['A','b'],['w','x']]

          w         x
A  2.706850  0.628133
b  0.651118 -0.319318

In [36]:
df.loc['A','w']

np.float64(2.706849839399938)

In [37]:
df>0

       w      x      y      z
A   True   True   True   True
b   True  False  False   True
c  False   True   True  False
d   True  False  False   True
e   True   True   True   True

In [38]:
df[df>0]

          w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
b  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
d  0.188695       NaN       NaN  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [39]:
df

          w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [40]:
df['w']>0

A     True
b     True
c    False
d     True
e     True
Name: w, dtype: bool

In [41]:
df[df['w']>0]

          w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [45]:
df[(df['w']>0)&(df['x']>0)&(df['y']>0)&(df['z']>0)]

          w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
e  0.190794  1.978757  2.605967  0.683509

In [46]:
df[df.gt(0).all(axis=1)]

          w         x         y         z
A  2.706850  0.628133  0.907969  0.503826
e  0.190794  1.978757  2.605967  0.683509

In [48]:
df=df[df['w']>0][['x','y']]

In [49]:
df

          x         y
A  0.628133  0.907969
b -0.319318 -0.848077
d -0.758872 -0.933237
e  1.978757  2.605967

In [57]:
boolser=df['w']>0
result=df[boolser]
myfit=['x','y']
result[myfit]

          x         y
A  1.693723 -1.706086
c  0.072960  0.638787