#### MultiIndex (hierarchical index) in pandas

In [8]:
import numpy as np
import pandas as pd
from numpy.random import randn, seed

seed(101)

In [9]:
# Index Levels
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]

hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [10]:
df=pd.DataFrame(randn(6,2),hier_index ,['a','b'])

In [11]:
df

             a         b
G1 1  2.706850  0.628133
   2  0.907969  0.503826
   3  0.651118 -0.319318
G2 1 -0.848077  0.605965
   2 -2.018168  0.740122
   3  0.528813 -0.589001

In [12]:
df.loc["G1"].loc[2]

          a         b
1  2.706850  0.628133
2  0.907969  0.503826
3  0.651118 -0.319318

In [13]:
df.loc["G1"].loc[2]

a    0.907969
b    0.503826
Name: 2, dtype: float64

In [15]:
df.index.names

FrozenList([None, None])

In [17]:
df.index.names=['Groups','Nums']

In [20]:
df

                    a         b
Groups Nums
G1     1     2.706850  0.628133
       2     0.907969  0.503826
       3     0.651118 -0.319318
G2     1    -0.848077  0.605965
       2    -2.018168  0.740122
       3     0.528813 -0.589001

In [21]:
df.loc["G2"].loc[2]["b"]

np.float64(0.7401220570561068)

In [22]:
df.xs('G1')

             a         b
Nums
1     2.706850  0.628133
2     0.907969  0.503826
3     0.651118 -0.319318

In [25]:
df.xs(1, level="Nums")

               a         b
Groups
G1      2.706850  0.628133
G2     -0.848077  0.605965