In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {'A': [1, 2, np.nan], 'B': [5, np.nan, np.nan], 'C': [1, 2, 3]}

df = pd.DataFrame(d)

df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [3]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [4]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [6]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [7]:
df.fillna(0)

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3